default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST", 'localhost') %>
  port: 3306
  username: <%= ENV.fetch("DATABASE_USER", 'jesher') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", 'jesher') %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", 'galgo') %>

production:
  <<: *default
  encoding: latin1
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>